Fh 212 be cron job expire commitment
F-Hostel-Management/F-Hostel-Management pull request #212
Opened 2022-06-18 06:38 UTC by dacnguyen9101

2022-06-19 12:27 UTC, huybui38 approved these changes

2022-06-19 12:27 UTC, huybui38 commented on Api/Controllers/Rest/RoomsController.cs
> +    [HttpGet("{roomId}/checkout")]
wtf GET

2022-06-19 12:28 UTC, huybui38 requested changes
chinh lại method get

2022-06-19 13:24 UTC, dacnguyen9101 commented on Api/Controllers/Rest/RoomsController.cs
> +    [HttpGet("{roomId}/checkout")]
à quên vc, hôm trc bảo test xong sửa mà quên

2022-06-20 11:05 UTC, huybui38 approved these changes

2022-06-20 11:05 UTC, merged